import { access, mkdir, readdir, readFile } from "node:fs/promises";
import path from "node:path";

import { atomicRecoveryArtifacts, atomicWriteFiles } from "./atomic-file-transaction";
import { parseInvocationRegistry, type InvocationClass } from "./invocation-registry";

const guard = "Use only when the user explicitly requests this skill.";
const siteUrl = "https://skills.tailrocks.com";
const repoBlob = "https://github.com/tailrocks/tailrocks-skills/blob/main";
const banner = "<!-- Generated by scripts/generate-docs.ts. Edit the skill source, not this file. -->";
const listStart = "<!-- skills:start -->";
const listEnd = "<!-- skills:end -->";

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

export interface Skill {
  readonly name: string;
  readonly title: string;
  readonly summary: string;
  readonly description: string;
  readonly argumentHint: string | undefined;
  readonly defaultPrompt: string | undefined;
  readonly invocationClass: InvocationClass;
  readonly body: string;
  readonly references: readonly string[];
  readonly templates: readonly string[];
}

export interface Generated {
  readonly file: string;
  readonly content: string;
}

export interface Group {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly skills: readonly string[];
}

export interface GroupedSkills {
  readonly group: Group;
  readonly skills: readonly Skill[];
}

export async function readCatalog(root: string): Promise<Group[]> {
  const parsed = JSON.parse(await readFile(path.join(root, "catalog.json"), "utf8")) as { groups?: unknown };
  if (!Array.isArray(parsed.groups)) throw new Error("catalog.json: groups must be an array");
  return parsed.groups as Group[];
}

/** Orders skills by catalog group, and refuses a catalog that does not cover the tree exactly once. */
export function groupSkills(groups: readonly Group[], skills: readonly Skill[]): GroupedSkills[] {
  const byName = new Map(skills.map((skill) => [skill.name, skill]));
  const placed = new Set<string>();
  const grouped: GroupedSkills[] = [];

  for (const group of groups) {
    const members: Skill[] = [];
    for (const name of group.skills) {
      const skill = byName.get(name);
      if (!skill) throw new Error(`catalog.json: group ${group.id} lists unknown skill ${name}`);
      if (placed.has(name)) throw new Error(`catalog.json: ${name} appears in more than one group`);
      placed.add(name);
      members.push(skill);
    }
    grouped.push({ group, skills: members });
  }

  const ungrouped = skills.filter((skill) => !placed.has(skill.name)).map((skill) => skill.name);
  if (ungrouped.length > 0) throw new Error(`catalog.json: no group contains ${ungrouped.join(", ")}`);
  return grouped;
}

/** Applies `transform` to prose only, leaving fenced blocks and inline code spans untouched. */
export function mapProse(source: string, transform: (text: string) => string): string {
  let fenced = false;
  return source
    .split("\n")
    .map((line) => {
      if (/^\s*```/.test(line)) {
        fenced = !fenced;
        return line;
      }
      if (fenced) return line;
      return line
        .split(/(`[^`]*`)/g)
        .map((part) => (part.startsWith("`") ? part : transform(part)))
        .join("");
    })
    .join("\n");
}

/** Rewrites repository-relative markdown links to absolute blob URLs. */
export function absoluteLinks(source: string, base: string): string {
  return mapProse(source, (text) =>
    text.replace(/\]\(([^)]+)\)/g, (match, target: string) =>
      /^(?:https?:|mailto:|#)/.test(target) ? match : `](${base}/${target})`,
    ),
  );
}

/** Escapes the characters MDX would otherwise read as expression or JSX syntax. */
export function escapeMdx(source: string): string {
  return mapProse(source, (text) =>
    text
      .replace(/<((?:https?|mailto):[^>\s]+)>/g, "[$1]($1)")
      .replace(/</g, "&lt;")
      .replace(/\{/g, "&#123;")
      .replace(/\}/g, "&#125;"),
  );
}

/** Strips the explicit-request guard and returns the first remaining sentence. */
export function summarize(description: string): string {
  const remainder = description.startsWith(guard)
    ? description.slice(guard.length).trim()
    : description.trim();
  const stop = remainder.search(/\.\s/);
  return stop === -1 ? remainder : remainder.slice(0, stop + 1);
}

function withoutGuard(description: string): string {
  return description.startsWith(guard) ? description.slice(guard.length).trim() : description.trim();
}

function titleFrom(body: string, name: string): string {
  return body.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? name;
}

function bodyWithoutTitle(body: string): string {
  return body.replace(/^#\s+.+\n+/, "").trimEnd();
}

async function listFiles(directory: string): Promise<string[]> {
  try {
    const entries = await readdir(directory, { withFileTypes: true, recursive: true });
    return entries
      .filter((entry) => entry.isFile())
      .map((entry) => path.relative(directory, path.join(entry.parentPath, entry.name)))
      .sort();
  } catch {
    return [];
  }
}

export async function readSkill(
  root: string,
  name: string,
  invocationClass: InvocationClass = "MANUAL_ONLY",
): Promise<Skill> {
  const skillDir = path.join(root, "skills", name);
  const source = await readFile(path.join(skillDir, "SKILL.md"), "utf8");
  const block = source.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!block) throw new Error(`${name}: invalid frontmatter`);
  const metadata = Bun.YAML.parse(block[1]) as Record<string, unknown>;
  const description = typeof metadata.description === "string" ? metadata.description : "";
  const body = source.slice(block[0].length).trim();

  let defaultPrompt: string | undefined;
  try {
    const openai = Bun.YAML.parse(await readFile(path.join(skillDir, "agents", "openai.yaml"), "utf8")) as {
      interface?: { default_prompt?: unknown };
    };
    if (typeof openai.interface?.default_prompt === "string") defaultPrompt = openai.interface.default_prompt;
  } catch {
    defaultPrompt = undefined;
  }

  return {
    name,
    title: titleFrom(body, name),
    summary: summarize(description),
    description: withoutGuard(description),
    argumentHint: typeof metadata["argument-hint"] === "string" ? metadata["argument-hint"] : undefined,
    defaultPrompt,
    invocationClass,
    body: bodyWithoutTitle(body),
    references: await listFiles(path.join(skillDir, "references")),
    templates: await listFiles(path.join(skillDir, "templates")),
  };
}

function assetSection(skill: Skill, link: (file: string) => string): string {
  const lines: string[] = [];
  if (skill.references.length > 0) {
    lines.push("", "## References", "");
    for (const file of skill.references) lines.push(`- [\`${file}\`](${link(`references/${file}`)})`);
  }
  if (skill.templates.length > 0) {
    lines.push("", "## Templates", "");
    for (const file of skill.templates) lines.push(`- [\`${file}\`](${link(`templates/${file}`)})`);
  }
  return lines.join("\n");
}

/** The documentation-site variant: the invocation is written for the reader's own client. */
function invocationPage(skill: Skill): string {
  const args = skill.argumentHint ?? "";
  const policy =
    skill.invocationClass === "MODEL_POLICY"
      ? [
          "This model-policy skill may load automatically only when its exact trigger",
          "matches work already in scope. Selection grants no authority beyond the",
          "active task. You may also name it directly where the client supports that:",
        ]
      : [
          "This skill never activates on its own. Name it in your request, written",
          "here for the agent selected in the sidebar:",
        ];
  const lines = [
    "## Invocation",
    "",
    ...policy,
    "",
    `<Invoke skill="${skill.name}"${args === "" ? "" : ` args="${escapeAttribute(args)}"`} />`,
  ];
  if (skill.argumentHint !== undefined) {
    lines.push("", `Arguments: \`${skill.argumentHint}\``);
  }
  return lines.join("\n");
}

function escapeAttribute(value: string): string {
  return value.replaceAll('"', "'");
}

/**
 * The part of the description the page has not already shown. Fumadocs renders the
 * frontmatter description under the title, so repeating it in the body is duplication —
 * but the sentences after the summary, usually the do-not-use clause, still have to land.
 */
function beyondSummary(skill: Skill): string {
  const rest = skill.description.slice(skill.summary.length).trim();
  return rest === "" ? "" : `\n${escapeMdx(rest)}\n`;
}

export function renderSkillOverview(skill: Skill): string {
  const base = `${repoBlob}/skills/${skill.name}`;
  return `---
title: ${JSON.stringify(`Tailrocks: ${skill.title}`)}
description: ${JSON.stringify(skill.summary)}
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

\`${skill.name}\` · [source](${base}/SKILL.md)
${beyondSummary(skill)}
${invocationPage(skill)}

## What it loads

The instructions the agent reads when you invoke this skill are on their own
page: [skill definition](/docs/skills/${skill.name}/definition). Read it when
you want to know exactly what the skill will do; you do not need it to use the
skill.
${escapeMdx(assetSection(skill, (file) => `${base}/${file}`))}
`;
}

export function renderSkillDefinition(skill: Skill): string {
  const base = `${repoBlob}/skills/${skill.name}`;
  const body = escapeMdx(absoluteLinks(skill.body, base));
  return `---
title: ${JSON.stringify(`Tailrocks: ${skill.title} — Skill definition`)}
description: ${JSON.stringify(`The instructions ${skill.name} loads, verbatim.`)}
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

Verbatim body of [\`${skill.name}\`](/docs/skills/${skill.name}), exactly as the
agent loads it. Source: [SKILL.md](${base}/SKILL.md).

---

${body}
`;
}

function groupTable(grouped: GroupedSkills, link: (skill: Skill) => string): string {
  const rows = grouped.skills.map(
    (skill) =>
      `| [\`${skill.name}\`](${link(skill)}) | ${skill.summary} | ${skill.invocationClass === "MODEL_POLICY" ? "Model policy" : "Manual only"} |`,
  );
  return [
    `### ${grouped.group.title}`,
    "",
    grouped.group.summary,
    "",
    "| Skill | What it does | Invocation |",
    "|---|---|---|",
    ...rows,
  ].join("\n");
}

export function renderSkillIndex(grouped: readonly GroupedSkills[]): string {
  const sections = escapeMdx(
    grouped.map((entry) => groupTable(entry, (skill) => `/docs/skills/${skill.name}`)).join("\n\n"),
  );
  return `---
title: Skills
description: "Every skill in the collection, grouped by the work it belongs to."
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

Invocation is registry-owned. Manual-only skills run only when named.
Model-policy skills may load only under their exact trigger when matching work
is already in scope, and selection grants no additional authority. When more
than one could apply, [choosing a skill](/docs/choosing) has the ownership boundaries.

${sections}
`;
}

export function renderSkillMeta(grouped: readonly GroupedSkills[]): string {
  const pages = ["index"];
  for (const entry of grouped) {
    pages.push(`---${entry.group.title}---`);
    for (const skill of entry.skills) pages.push(skill.name);
  }
  return `${JSON.stringify({ title: "Skills", pages }, null, 2)}\n`;
}

export function renderRootList(grouped: readonly GroupedSkills[]): string {
  const sections = grouped
    .map((entry) => groupTable(entry, (skill) => `${siteUrl}/docs/skills/${skill.name}`))
    .join("\n\n");
  return `${listStart}

${sections}

${listEnd}`;
}

export function replaceRootList(readme: string, list: string): string {
  const start = readme.indexOf(listStart);
  const end = readme.indexOf(listEnd);
  if (start === -1 || end === -1)
    throw new Error(`README.md is missing the ${listStart} / ${listEnd} markers`);
  return `${readme.slice(0, start)}${list}${readme.slice(end + listEnd.length)}`;
}

export function renderInstallPage(install: string): string {
  const body = escapeMdx(absoluteLinks(install.replace(/^#\s+.+\n+/, "").trimEnd(), repoBlob));
  return `---
title: Installing
description: "Install the collection in Claude Code, Codex, OpenCode, Grok Build, Kimi Code, Antigravity, or Amp."
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

${body}
`;
}

export async function generate(root: string): Promise<Generated[]> {
  const directories = (await readdir(path.join(root, "skills"), { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const names: string[] = [];
  for (const name of directories) {
    if (await exists(path.join(root, "skills", name, "SKILL.md"))) names.push(name);
  }
  let registry: unknown;
  try {
    registry = JSON.parse(await readFile(path.join(root, "invocation-registry.json"), "utf8"));
  } catch {
    throw new Error("invocation-registry.json: missing or invalid JSON");
  }
  const invocation = parseInvocationRegistry(registry, names);
  if (invocation.errors.length > 0) throw new Error(invocation.errors.join("\n"));
  const skills: Skill[] = [];
  for (const name of names) skills.push(await readSkill(root, name, invocation.classes.get(name)!));
  const grouped = groupSkills(await readCatalog(root), skills);

  const output: Generated[] = [];
  for (const skill of skills) {
    output.push({
      file: path.join("docs", "content", "docs", "skills", skill.name, "index.mdx"),
      content: renderSkillOverview(skill),
    });
    output.push({
      file: path.join("docs", "content", "docs", "skills", skill.name, "definition.mdx"),
      content: renderSkillDefinition(skill),
    });
  }
  output.push({
    file: path.join("docs", "content", "docs", "skills", "index.mdx"),
    content: renderSkillIndex(grouped),
  });
  output.push({
    file: path.join("docs", "content", "docs", "skills", "meta.json"),
    content: renderSkillMeta(grouped),
  });
  output.push({
    file: path.join("docs", "content", "docs", "install.mdx"),
    content: renderInstallPage(await readFile(path.join(root, "INSTALL.md"), "utf8")),
  });
  output.push({
    file: "README.md",
    content: replaceRootList(await readFile(path.join(root, "README.md"), "utf8"), renderRootList(grouped)),
  });
  return output;
}

/**
 * Finds diagrams drawn as text instead of Mermaid. A fenced block qualifies when it
 * spans more than one line and uses flow arrows. Directory trees are drawings of a
 * filesystem, not of a flow, so box-drawing characters exempt a block.
 */
export function textDiagrams(source: string): number[] {
  const lines = source.split("\n");
  const found: number[] = [];
  let opened: number | undefined;
  let language = "";
  let body: string[] = [];

  for (const [index, line] of lines.entries()) {
    const fence = line.match(/^\s*```(\w*)/);
    if (!fence) {
      if (opened !== undefined) body.push(line);
      continue;
    }
    if (opened === undefined) {
      opened = index;
      language = fence[1] ?? "";
      body = [];
      continue;
    }
    const isTree = body.some((entry) => /[├└│]/.test(entry));
    const hasArrows = body.some((entry) => /[→⇄↕⟶]|-->/.test(entry));
    if (language !== "mermaid" && hasArrows && !isTree && body.length > 1) found.push(opened + 1);
    opened = undefined;
  }
  return found;
}

/** Fumadocs content is MDX only; a plain .md page silently renders without component support. */
export async function strayMarkdown(root: string): Promise<string[]> {
  const contentRoot = path.join(root, "docs", "content");
  const stray: string[] = [];
  for (const file of await listFiles(contentRoot)) {
    if (file.endsWith(".md")) stray.push(path.join("docs", "content", file));
  }
  return stray.sort();
}

async function currentContent(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch {
    return undefined;
  }
}

async function main(args: readonly string[]): Promise<number> {
  const root = path.resolve(import.meta.dir, "..");
  if (!(args.length === 0 || (args.length === 1 && args[0] === "--check"))) {
    console.log(
      JSON.stringify({
        schema: "tailrocks.generate-docs/v1",
        outcome: "refused",
        code: "invalid_arguments",
        mutations: [],
        detail: "usage: generate-docs.ts [--check]",
      }),
    );
    return 2;
  }
  const check = args[0] === "--check";
  const stray = await strayMarkdown(root);
  if (stray.length > 0) {
    throw new Error(`documentation pages must be .mdx, not .md: ${stray.join(", ")}`);
  }

  const drawn: string[] = [];
  for (const page of await listFiles(path.join(root, "docs", "content"))) {
    if (!page.endsWith(".mdx")) continue;
    const file = path.join("docs", "content", page);
    for (const line of textDiagrams(await readFile(path.join(root, file), "utf8"))) {
      drawn.push(`${file}:${line}`);
    }
  }
  if (drawn.length > 0) {
    throw new Error(`draw as mermaid, not text: ${drawn.join(", ")}`);
  }
  const generated = await generate(root);
  const stale: string[] = [];
  const writes = [];
  for (const { file, content } of generated) {
    const target = path.join(root, file);
    const current = await currentContent(target);
    if (current === content) continue;
    stale.push(file);
    if (check) continue;
    await mkdir(path.dirname(target), { recursive: true });
    writes.push({ file: target, expected: current ?? null, content });
  }
  if (check && stale.length > 0) {
    throw new Error(`generated docs are out of date: ${stale.join(", ")}`);
  }
  await atomicWriteFiles(writes);
  console.log(
    JSON.stringify({
      schema: "tailrocks.generate-docs/v1",
      outcome: "success",
      code: check ? "checked" : "written",
      checked: generated.length,
      mutations: stale,
      recovery_artifacts: [],
      detail: check ? `checked ${generated.length} generated files` : `wrote ${stale.length} generated files`,
    }),
  );
  return 0;
}

if (import.meta.main) {
  try {
    process.exit(await main(process.argv.slice(2)));
  } catch (error) {
    console.log(
      JSON.stringify({
        schema: "tailrocks.generate-docs/v1",
        outcome: "failed",
        code: "generation_failed",
        mutations: [],
        recovery_artifacts: atomicRecoveryArtifacts(error),
        detail: error instanceof Error ? error.message : String(error),
      }),
    );
    process.exit(1);
  }
}
